### ISSUE TITLE
When trying to use with a table with ColumnStore an exception is thrown

### ISSUE THREAD

**Issue by idanmashaal** [lucazav/SqlServerPartitionManagementUtility#1]
Hi,
Consider the following schema on SQL Server 2014 SP2.
I was able to reproduce this in several instances.
Tried using the 2014 and 2012 versions of the "ManagePartition.exe" tool but all yield the same results.

USE [testDb]
GO

CREATE TABLE [dbo].[Logs]([Id] [bigint] IDENTITY%281,1%29 NOT NULL,
    [DATE] [datetime2]%287%29 NOT NULL,
    [LEVEL] [nvarchar]%2850%29 NULL,
    [Thread] [nvarchar]%28100%29 NULL,
    [Logger] [nvarchar]%28100%29 NULL,
    [Message] [nvarchar]%284000%29 NULL,
    [EXCEPTION] [nvarchar]%284000%29 NULL,
    [DOMAIN] [nvarchar]%28255%29 NULL,
    [USER] [nvarchar]%2850%29 NULL,
    [Host] [nvarchar]%2850%29 NULL,
    [Class] [nvarchar]%28255%29 NULL,
    [Method] [nvarchar]%28255%29 NULL,
    [File] [nvarchar]%28255%29 NULL,
    [Line] [int] NULL) ON [psc_Logs_DATETIME2]([DATE])

GO

CREATE CLUSTERED COLUMNSTORE INDEX [cci_Logs] ON [dbo].[Logs] 
WITH (
  DROP_EXISTING = OFF,
  DATA_COMPRESSION = COLUMNSTORE
) ON [psc_Logs_DATETIME2]([DATE])
GO

When running the command: 
ManagePartition.exe /Command:ClearPartition /Database:myDb /Schema:dbo /PartitionTable:Logs /PartitionNumber:2 /Keep- /ScriptOption:o

The following error and exeptions are raised:
Microsoft.SqlServer.Management.Smo.FailedOperationException: Cannot set ColumnStore compression.
   at Microsoft.SqlServer.Management.Smo.PhysicalPartition.set_DataCompression(DataCompressionType value)
   at Microsoft.SqlServer.Management.Smo.PhysicalPartition..ctor(SqlSmoObject parent, Int32 partitionNumber, DataCompressionType dataCompressionType)
   at PartitionManagement.PartitionManager.CreateStgTable()
   at PartitionManagement.App.Run(AppArgs& parsedArgs)
Cannot set ColumnStore compression.

Thanks,
Idan.

**Comment by jzabroski** [comment]
@idanmashaal Did you ever work around this issue?  Can you please capture a trace for me.  Thanks

**Comment by lucazav** [comment]
Sorry guys, but I can't maintain this project anymore. If you could fix these bug, you're welcome as contributors of this project.
Thanks!

**Comment by nalvio** [comment]
Hi, @lucazav!
I think I can help to update this repository and solve some problems as contributor...
I've been using ManagePartition for more than 5 years.

Regards!

**Comment by lucazav** [comment]
Hi @nalvio ,
this is a great news! I'll add you as a contributor!
Thank you for your support.

**Comment by nalvio** [comment]
Glad to hear from you!
Thank you so much!
